### ISSUE TITLE
webdav备份恢复失败

### ISSUE THREAD

**Issue by Http-200** [lollipopkit/flutter_gpt_box#4]
日志如下：
Download webdav backup failed: WebdavErr<WebdavErrType.generic>:DioException [bad response]:null
Error:Found

结合这个日志我去查看了下源码，在`webdav.dart`文件的78行，result不为空，则提前终止函数。这里是不是有问题，应该是`result == null`？另外，希望可以在日志上添加个复制按钮。非常期待您的回复，谢谢！！！

**Comment by lollipopkit** [comment]
- 应该不是这里的逻辑问题，因为 result 的类型是 WebdavErr，可能是 WebDAV server 不兼容
- log 复制按钮已加

**Comment by Http-200** [comment]
> * 应该不是这里的逻辑问题，因为 result 的类型是 WebdavErr，可能是 WebDAV server 不兼容
> * log 复制按钮已加

我是用alist挂载网盘转的webdav，试过备份是正常的

**Comment by lollipopkit** [comment]
备份（上传）正常，但是没法下载...？好奇怪的问题

**Comment by Http-200** [comment]
> 备份（上传）正常，但是没法下载...？好奇怪的问题

抱歉，这两天没看邮件。我也觉得奇怪，我更新了版本，这是新版本，报的错误日志。
```txt
[INFO][App]: Update ignored: 65 >= 40

[INFO][App]: Upload webdav backup success

[WARNING][Webdav]: Download gptbox_bak.json failed
DioException [bad response]: null
Error: Found
#0      _WdDio.wdReadWithStream (package:webdav_client/src/client.dart:520)
<asynchronous suspension>
#1      WebdavClient.readFile (package:webdav_client/src/client.dart:185)
<asynchronous suspension>
#2      Webdav.download (package:flutter_chatgpt/core/util/sync/webdav.dart:66)
<asynchronous suspension>
#3      _onTapWebdavDl (package:flutter_chatgpt/view/page/backup/func/webdav.dart:75)
<asynchronous suspension>


[WARNING][App]: Download webdav backup failed: WebdavErr<WebdavErrType.generic>: DioException [bad response]: null
Error: Found
```

**Comment by PaperCube** [comment]
这个问题似乎是由于 alist 使用 302 重定向导致的，而 GPTBox 的 webdav 依赖并不支持这样处理。我看 alist 似乎有[本机代理模式](https://alist.nn.ci/zh/guide/drivers/common.html#webdav-%E7%AD%96%E7%95%A5) ，建议将 alist 的 webdav 策略改成本机代理模式再试一下？

**Comment by Http-200** [comment]
> 这个问题似乎是由于 alist 使用 302 重定向导致的，而 GPTBox 的 webdav 依赖并不支持这样处理。我看 alist 似乎有[本机代理模式](https://alist.nn.ci/zh/guide/drivers/common.html#webdav-%E7%AD%96%E7%95%A5) ，建议将 alist 的 webdav 策略改成本机代理模式再试一下？

谢谢，可以了，是这个原因，改了本地代理就可以了。另外，你有考虑添加保存多组key支持吗？现在的客户端，像是chatbox都不支持。如果自己有多个key的，可以直接保存在软件里，同步到网盘保存了。

**Comment by lollipopkit** [comment]
> 谢谢，可以了，是这个原因，改了本地代理就可以了。另外，你有考虑添加保存多组key支持吗？现在的客户端，像是chatbox都不支持。如果自己有多个key的，可以直接保存在软件里，同步到网盘保存了。

会做，但优先写其它功能（文生图、图生图...）

**Comment by Http-200** [comment]
> > 谢谢，可以了，是这个原因，改了本地代理就可以了。另外，你有考虑添加保存多组key支持吗？现在的客户端，像是chatbox都不支持。如果自己有多个key的，可以直接保存在软件里，同步到网盘保存了。
> 
> 会做，但优先写其它功能（文生图、图生图...）

好的，谢谢！！！
